config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'login#index'

  # 各種OAuthのコールバック用
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def index
  end

  def login
  end

  def callback
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login, raise: false

  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        sorcery_fetch_user_hash(provider)
        create_user(provider)
        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end

  private

  # id_tokenからemailを取得
  # 申請していない場合は取得できない
  def create_user(provider_name)
    attrs = user_attrs(@provider.user_info_mapping, @user_hash)
    id_token = @access_token.params['id_token']
    id_token_payload = JWT.decode(id_token,@provider.secret)
    Rails.logger.info id_token_payload.inspect
    email = id_token_payload.first['email']
    attrs['email'] = email || 'example@test-mail.jp'

    @user = user_class.create_from_provider(provider_name, @user_hash[:uid], attrs)
  end

  def auth_params
    params.permit(:code, :provider, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
      <% flash.each do |message_type, message| %>
        <%= message %>
      <% end %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<%= link_to image_tag("btn_login_base.png", alt: "LINEログイン"), auth_at_provider_path(:provider => :line) %>

app/views/oauths/callback.html.erb
<h1>Oauths#callback</h1>
<p>Find me in app/views/oauths/callback.html.erb</p>

app/views/oauths/oauth.html.erb
<h1>Oauths#oauth</h1>
<p>Find me in app/views/oauths/oauth.html.erb</p>